server.port=8086
spring.application.name=report-service

# Oracle DB Connection Properties
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:report_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:reportpwd}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
