server.port=8080

spring.application.name=account-service

# Database Connection (PostgreSQL)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/acct_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.tomcat.max-active=10
spring.datasource.tomcat.initial-size=1
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=true

# Database initialization
spring.sql.init.mode=always

# Springdoc OpenAPI properties
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

# Logging
logging.level.root=INFO
logging.level.com.rapidx.accoutservice=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

macvault.auth.enable=true
macVault.path=/pkgs/secrets/app/
superUser=ucnt_ping_ext_np_user
management.endpoints.enabled-by-default=true
management.endpoint.health.show-details=ALWAYS
management.endpoints.web.exposure.include=health, info, metrics
management.endpoints.web.base-path=/actuator

server.session.timeout=600000
server.tomcat.connectionTimeout=-1

# Email Service Client properties
bypassPingAuth=true
email-service.url=http://localhost:8083

#Ping token attribute for external
ping.external.token.key=FMACJWT
#Ping token attribute for internal
ping.internal.token.key=FHLMCJWT
#Ping external JWKS URL for token verification
ping.external.jwks.url=https://securedev.fhlmc.com/pa/authtoken/JWKS
#Ping internal JWKS URL for token verification
ping.internal.jwks.url=https://securedev.fhlmc.com/pa/authtoken/JWKS
#ROPC token key
ropc.token.key=Authorization
#ROPC JWKS URL for token verification
ropc.jwks.url=https://authdev.fhlmc.com/ext/fhlmc/JWKS
jwks.cached=true
db.cred.file.location=/etc/app/dbcred
enable.hashcorp.db=true

#AMQ settings
spring.activemq.broker-url=failover:(ssl://em.itn31.geonp.fhlmc.com:61617?socket.verifyHostName=false)?initialReconnectDelay=120&randomize=false
spring.activemq.user=ucount_np_ebm_user
spring.activemq.queue-name=SF-BA0352-EBMQueue.local
spring.activemq.in-memery=true
spring.activemq.pool.enabled=false
hashicorp.ad.amq.path=/etc/app/amqcred
broker=ITN31_LDAP
spring.activemq.redelivery-policy.maximum-redeliveries=5
spring.activemq.redelivery-policy.redelivery-delay=2000


