server.port=8082

spring.application.name=aggregator-service

# Database Connection (H2 for simple setup)
spring.datasource.url=jdbc:h2:mem:aggdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS ba0352
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Downstream services URL config
auth-service.url=${AUTH_SERVICE_URL:http://localhost:8081}
account-service.url=${ACCOUNT_SERVICE_URL:http://localhost:8080}
report-service.url=${REPORT_SERVICE_URL:http://localhost:8086}

logging.level.root=INFO
logging.level.com.rapidx.aggregator=DEBUG

# OIM Sync Config
oim.sync.bypass=false
api.retries.max=3
api.retries.delay=2
